package com.zeta.uber.booking;

public enum RequestStatus {

	REQUEST_RECEIVED, CAB_LOCAIONS_REQUESTTED, 
	CAB_LOCATIONS_RETRIEVED,
	REQUEST_SENT_TO_DRIVER,
	DRIVER_ACCEPTED_REQUEST,
	DRIVER_REJECTED_REQUEST,
	PASSENGER_REQUESTED_CANCEL,
	BOOKING_RESPONSE
}
